FROM node:22.9.0

ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

RUN apt-get update && \
    apt-get install -y chromium

RUN npm install -g npm

WORKDIR /usr/src/app

COPY package*.json /usr/src/app/
COPY mon-aide-cyber-api/package.json /usr/src/app/mon-aide-cyber-api/package.json

RUN npm install

COPY mon-aide-cyber-api/ /usr/src/app/mon-aide-cyber-api/

CMD ["npm", "run", "dev", "-w", "mon-aide-cyber-api"]
