FROM node:18

RUN apt-get update

RUN npm install -g npm

WORKDIR /usr/src/app

COPY package*.json /usr/src/app/
COPY mon-aide-cyber-api/package.json /usr/src/app/mon-aide-cyber-api/package.json

RUN npm install

COPY mon-aide-cyber-api/ /usr/src/app/mon-aide-cyber-api/

CMD ["npm", "run", "start", "-w", "mon-aide-cyber-api"]
