name: Node.js CI
permissions: {}

on:
  pull_request:
  push:
    branches: [main]

env:
  URL_SERVEUR_BASE_DONNEES: postgres://postgres@localhost:5433
  URL_JOURNALISATION_BASE_DONNEES: postgres://postgres@localhost:5433

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5433:5432

    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          persist-credentials: false
      - name: Configurer Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
      - name: Installe pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: 10.34.5
      - name: (TOUS) Installe les dépendances
        run: pnpm install --frozen-lockfile
      - name: Vérifie le prettier
        run: pnpm run format:verifie
      - name: Construis le back
        run: pnpm -F mon-aide-cyber-api run build
      - name: Construis le front
        run: pnpm -F mon-aide-cyber-ui run build
      - name: Initialise l’environnement de test avec le service Postgres
        run: pnpm -F mon-aide-cyber-api run ci:initialise
      - name: Exécute les tests
        run: pnpm run test

      - name: Rapport des tests
        uses: dorny/test-reporter@df6247429542221bc30d46a036ee47af1102c451 # v2.7.0
        if: ${{ !cancelled() }} # On force l'exécution même si l'étape précédente a échoué
        with:
          name: Tests vitest
          path: mon-aide-cyber-api/vitest-junit.xml,mon-aide-cyber-ui/vitest-junit.xml
          reporter: jest-junit
